ex/ex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("myapp.urls")),
    path("admin/", admin.site.urls),
]

ex/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.user_logout, name="logout"),
    path("update/<int:pk>/", views.update_tip, name="update_tip"),
]

ex/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission


class CustomUser(AbstractUser):
    reputation = models.IntegerField(default=0)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        can_downvote_perm = Permission.objects.get(codename="can_downvote")
        can_delete_perm = Permission.objects.get(codename="delete_tip")

        if self.reputation >= 15:
            self.user_permissions.add(can_downvote_perm)
        else:
            self.user_permissions.remove(can_downvote_perm)

        if self.reputation >= 30:
            self.user_permissions.add(can_delete_perm)
        else:
            self.user_permissions.remove(can_delete_perm)



class Tip(models.Model):
    content = models.TextField()
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    upvotes = models.ManyToManyField(CustomUser, related_name="upvotes")
    downvotes = models.ManyToManyField(CustomUser, related_name="downvotes")

    class Meta:
        permissions = [
            ("can_downvote", "Can downvote"),
        ]

    def delete(self, *args, **kwargs):
        # Calculate reputation change
        reputation_loss = 5 * self.upvotes.count()
        reputation_gain = 2 * self.downvotes.count()
        reputation_change = reputation_gain - reputation_loss

        # Update author's reputation
        self.author.reputation += reputation_change
        self.author.save()

        # Proceed with the standard delete process
        super().delete(*args, **kwargs)

ex/myapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser
from .models import Tip


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Username"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        )
    )


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ("username", "password")

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("The two password fields must match.")

        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data["username"]
        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists.")
        return username


class TipForm(forms.ModelForm):
    class Meta:
        model = Tip
        fields = ("content",)

ex/myapp/views.py
import datetime
import random
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from .models import Tip

from .forms import SignUpForm, TipForm, UserLoginForm
from .signals import vote


# Create your views here.
def index(request):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect(reverse("myapp:index"))
        form = TipForm(request.POST)
        if form.is_valid():
            tip = form.save(commit=False)
            tip.author = request.user
            tip.save()
            return redirect("/")
    else:
        form = TipForm()

    current_time = datetime.datetime.now().timestamp()
    user_session = request.session.get("user", None)

    if request.user.is_authenticated:
        uname = request.user.get_full_name() or request.user.username
    elif user_session is None or user_session["time"] + 42 < current_time:
        request.session["user"] = {
            "name": random.choice(settings.SESSION_NAMES),
            "time": current_time,
        }
        uname = request.session["user"]["name"]
    else:
        uname = user_session["name"]

    tips = Tip.objects.all()
    for i in range(len(tips)):
        tips[i].upvotesCount = len(tips[i].upvotes.all())
        tips[i].downvotesCount = len(tips[i].downvotes.all())

    return render(
        request, "myapp/index.html", {"uname": uname, "tips": tips, "form": form}
    )


def user_login(request):
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
    else:
        form = UserLoginForm()
    return render(request, "myapp/login.html", {"form": form})


def signup(request):
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            user.save()
            login(request, user)
            return redirect("/")
    else:
        form = SignUpForm()
    return render(request, "myapp/signup.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect("/")


def update_tip(request, pk):
    if request.method != "POST":
        return redirect("/")
    if not request.user.is_authenticated:
        return redirect("/")
    tip = get_object_or_404(Tip, pk=pk)
    action = request.POST.get("action")
    if action == "delete":
        if request.user == tip.author or request.user.has_perm("myapp.delete_tip"):
            tip.delete()
    elif action == "upvote":
        if request.user in tip.upvotes.all():
            tip.upvotes.remove(request.user)
            vote.send(Tip, bonus=-5, user=tip.author)
        else:
            if request.user in tip.downvotes.all():
                tip.downvotes.remove(request.user)
                vote.send(Tip, bonus=2, user=tip.author)
            tip.upvotes.add(request.user)
            vote.send(Tip, bonus=5, user=tip.author)
        tip.save()
    elif action == "downvote":
        if request.user == tip.author or request.user.has_perm("myapp.can_downvote"):
            if request.user in tip.downvotes.all():
                tip.downvotes.remove(request.user)
                vote.send(Tip, bonus=2, user=tip.author)
            else:
                if request.user in tip.upvotes.all():
                    tip.upvotes.remove(request.user)
                    vote.send(Tip, bonus=-5, user=tip.author)
                tip.downvotes.add(request.user)
                vote.send(Tip, bonus=-2, user=tip.author)
            tip.save()
    return redirect("/")

ex/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Unchained</title>
  <!-- Load Bootstrap4 CSS via django-bootstrap4 -->
  {% load bootstrap5 %}
  {% bootstrap_css %}
</head>

<body>

  {% load bootstrap5 %}

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand ms-4" href="{% url 'myapp:index' %}">Unchained</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:login' %}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:signup' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <!-- Content Block -->
  <div class="container">
    {% block content %}
    <!-- Your page content goes here -->
    {% endblock %}
  </div>


</body>

</html>

ex/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% load bootstrap5 %}

{% block content %}
<nav>Hello {{ uname }}!</nav>
{% if request.user.is_authenticated %}
<form method="post" class="my-4">
  {% csrf_token %}
  {% bootstrap_form_errors form type="non_fields" %}

  {% bootstrap_field form.content label="Content" placeholder=form.content.label %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endif %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Author</th>
      <th scope="col">Tip</th>
      <th scope="col">Upvotes</th>
      <th scope="col">Downvotes</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for tip in tips %}
    <tr>
      <th>{{ tip.date }}</th>
      <th>{{ tip.author }} ({% if tip.author.reputation >= 30 %}Expert{% elif tip.author.reputation >= 15 %}Amateur{% else %}Noob{% endif %})</th>
      <th>{{ tip.content }}</th>
      <th>{{ tip.upvotesCount }}</th>
      <th>{{ tip.downvotesCount }}</th>
      <th>
        <form method="post" action="{% url 'myapp:update_tip' tip.id %}">
          {% csrf_token %}
          <button name="action" value="upvote" type="submit" class="btn btn-primary">Upvote</button>
          {% if perms.myapp.can_downvote or request.user == tip.author %}
          <button name="action" value="downvote" type="submit" class="btn btn-primary">Downvote</button>
          {% endif %}
          {% if perms.myapp.delete_tip or request.user == tip.author %}
          <button name="action" value="delete" type="submit" class="btn btn-danger">Delete</button>
          {% endif %}
        </form>
      </th>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

ex/myapp/templates/myapp/login.html
{% extends "myapp/base.html" %}

{% load bootstrap5 %}

{% block content %}
<div class="container mt-5">
    <form method="post" class="form-signin">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="text-center">
            <button type="submit" class="btn btn-primary btn-block">Login</button>
        </div>
    </form>
</div>
{% endblock %}

ex/myapp/templates/myapp/signup.html
<!-- templates/signup.html -->

{% extends "myapp/base.html" %}

{% load bootstrap5 %}

{% block content %}
<form method="post" class="my-4">
  {% csrf_token %}
  {% bootstrap_form_errors form type="non_fields" %}

  {% bootstrap_field form.username label="Username" placeholder=form.username.label %}
  {% bootstrap_field form.password label="Password" placeholder=form.password.label field_class="password" %}
  {% bootstrap_field form.confirm_password label="Confirm Password" placeholder=form.confirm_password.label field_class="password" %}

  <button type="submit" class="btn btn-primary">Sign up</button>
</form>
{% endblock %}